name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:    
      - name: Get Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_PAT }}
          template: classic
          base: header, metadata
          config_order: base.header, isocalendar, languages, achievements
          config_timezone: Australia/Brisbane
          plugin_languages: yes
          plugin_languages_ignored: tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
